name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8
        run_install: false

    - name: Build 2.x components
      run: |
        cd versions/2.7
        pnpm install --no-frozen-lockfile
        pnpm run build

    - name: Build 3.x components
      run: |
        cd versions/3
        pnpm install --no-frozen-lockfile
        pnpm run build

    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile
    
    - name: Vitest
      run: pnpm test

    - name: Publish
      run: node ./scripts/publish.js
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
